name: rl_robot
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - gymnasium==1.2.3
      - gymnasium-robotics==1.4.2
      - mujoco==3.8.1
      - stable_baselines3==2.8.0
      - torch==2.11.0
      - numpy
      - matplotlib
      - imageio
      - pillow
      - tensorboard
